-- SQL Migration Script to update 'member_position' ENUM in Supabase / PostgreSQL
-- Adds Head and Co-Head values for all 7 candidate departments

ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'TECHNICAL_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CO-TECHNICAL_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'EVENT_MANAGEMENT_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CO-EVENT_MANAGEMENT_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'FINANCE_&_MARKET_RELATIONS_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CO-FINANCE_&_MARKET_RELATIONS_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CREATIVE_&_PHOTOGRAPHY_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CO-CREATIVE_&_PHOTOGRAPHY_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'PROMOTION_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CO-PROMOTION_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'ANCHORING_HEAD';
ALTER TYPE member_position ADD VALUE IF NOT EXISTS 'CO-ANCHORING_HEAD';
